spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:trademart
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: 86400000 # 24 hours

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:h2:mem:trademart-qa
  jpa:
    show-sql: false

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/trademart
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

server:
  port: 8082

# FIX Protocol Configuration
fix:
  config:
    path: config/FIX44.xml
    sender-comp-id: SIMULATOR
    target-comp-id: CLIENT
    heartbeat-interval: 30
    reconnect-interval: 5

# OUCH Protocol Configuration
ouch:
  port: 5000
  max-message-size: 65536

# ITCH Market Data Configuration
itch:
  snapshot-interval: 1000 # milliseconds
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META